AUDIO_ROOT := $(srctree)/techpack/audio

ifeq ($(CONFIG_ARCH_SUN), y)
	include $(AUDIO_ROOT)/config/sunauto.conf
	export INCS += -include $(AUDIO_ROOT)/config/sunautoconf.h
endif

obj-y := dsp/ ipc/ soc/ asoc/
